config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

 	root to: "home#index"
 	resources :images
 	resources :avatars
  	
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
	belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :picture, PictureUploader

	validates :description, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_one :avatars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_action :configure_devise_params, if: :devise_controller?

	# comentario prueba

  def configure_devise_params
  	devise_parameter_sanitizer.permit(:sign_up) do |user|
  		user.permit(:name, :email, :password, :password_confirmation)
  	end
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
	def index
		if user_signed_in?
  		@avatar = Avatar.where user_id: current_user.id
  		end
	end

	def new 
		@avatar = Avatar.new
	end

	def create
		@avatar = current_user.avatar.new avatar_params

		if @avatar.save
			return redirect_to home_index_path
		end

		render :new
	end

	private

	def avatar_params
		params.require(:avatar).permit(:avatar)
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if user_signed_in?
  		@images = Image.paginate(page: params[:page], per_page: 9)
  					   .order(id: :desc)
  				   	   .where user_id: current_user.id
  	end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:show, :update, :destroy, :edit]
	def index
		if user_signed_in?
  		@images = Image.paginate(page: params[:page], per_page: 9)
  					   .order(id: :desc)
  				   	   .where user_id: current_user.id
  		end
	end


	def new 
		@image = Image.new
	end

	def create
		@image = current_user.images.new image_params

		if @image.save
			return redirect_to home_index_path
		end

		render :new
	end

	def show
	end

	def edit
	end

	def update 
		@image.update image_params
		redirect_to home_index_path
	end

	def destroy
		@image.destroy
		redirect_to home_index_path
	end

	private

	def image_params
		params.require(:image).permit :description, :picture
	end

	def set_image 
		@image = Image.find params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/avatars/new.html.erb
<div class="form-group">
	<%= form_for @avatar do |f| %>
		<%= f.label :avatar %> <br>
		<%= f.file_field :avatar %> 
		<br>
		<%= f.submit 'Subir', :class => 'btn btn-primary' %>
	<% end %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
		<% if user_signed_in? %>
				
			<div class="row">
				<div class="col-4">
					<div class="container" class="media mt-3">
						<img class="rounded-circle" style="width: 150px; height: 150px; margin-bottom: 10px; margin-left: 180px;" src="http://alumni.crg.eu/sites/default/files/default_images/default-picture_0_0.png" >
					
					</div>
				</div>
				<div class="col-8">
					<h1><%= current_user.name %></h1>
					<div>
						<ul class="nav">
							<li class="margin-right">
								<p> <strong><%= @images.count %></strong> publicaciones</p>
							</li>
							<li class="margin-right">
								<p> <strong> <%= rand(1000)%> </strong> seguidores</p>
							</li>
							<li class="margin-right">
								<p> <strong> <%= rand(700) %> </strong> seguidos</p>
							</li>
							
						</ul>
					</div>
				</div>
			</div>
			<div class="row" id="images">
				<%= render @images %>
			</div>
			<%= will_paginate @images %>
		<% else %>
			<h1 align="center">Sholgram</h1>
		<% end %>
</body>
</html>

app/views/home/index.js.erb
$('#images').append('<%= j render @images %>')

<% if @images.next_page %>
	$('.pagination').replaceWith('<%= j will_paginate @images %>')
<% else %>
	$('.pagination').remove();
<% end %>

app/views/images/_form.html.erb
<div class="form-group">
	<%= form_for @image, builder: CustomFormBuilder do |f| %>
		<%= f.form_error %>
		<%= f.label :description %> <br>
		<%= f.text_field :description, class: 'form-control' %>
		<%= f.field_error :description %>
		<br>
		<%= f.label :picture %> <br>
		<%= f.file_field :picture %> 
		<br>
		<%= f.submit 'Enviar', :class => 'btn btn-primary' %>

	<% end %>
</div>

app/views/images/_image.html.erb
<div class="col-4">
	<figure class="figure">
	   <%= image_tag image.picture.medium.url, class: 'figure-img img-fluid rounded' %>
	  <figcaption class="figure-caption">
	  	<%= image.description %>.
		<%= link_to t('.edit_link'), edit_image_path(image) %>
		<%= link_to t('.remove_link'), image, method: :delete, data:{ confirm: 'sure?'}%>
	  </figcaption>
	</figure>
</div>

app/views/images/edit.html.erb
<div class="container">
	<h1>Editar imagen</h1>
	<%= render 'form'%>
</div>

app/views/images/index.html.erb
<div class="container">
	<% if user_signed_in?  %>
			<h1 style="text-align: center;">Sholgram</h1>
			
			<div class="row">
				<div class="col-4">
					
				</div>
				<div class="col-8">
					<h1><%= current_user.name %></h1>
					<div>
						<ul class="nav">
							<li class="margin-right">
								<p> <strong><%= @images.count %></strong> publicaciones</p>
							</li>
							<li class="margin-right">
								<p> <strong> <%= rand(1000)%> </strong> seguidores</p>
							</li>
							<li class="margin-right">
								<p> <strong> <%= rand(700) %> </strong> seguidos</p>
							</li>
							
						</ul>
					</div>
				</div>
			</div>
			<div class="row">
				<%= render @images %>
			</div>
			<%= will_paginate @images %>
		<% else %>
			<h1 align="center">Sholgram</h1>
		<% end %>
</div>

app/views/images/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<div class="container">
		<h1>Crear imagen</h1>
		<%= render 'form'%>
	</div>

</body>
</html>

app/views/images/show.html.erb
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sholgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: white">

    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Sholgram 8.0</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"><%= link_to 'Inicio', home_index_path, class: "nav-link" %> <span class="sr-only">(current)</span></a>
          </li>

          <%- if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Agregar Imagen', new_image_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Salir', destroy_user_session_path, method: :delete,
              class: "nav-link" %>
            </li> 

          <% else %>
            <li class="nav-item">
              <%= link_to ' Iniciar ', new_user_session_path,
              class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to ' Registrarme ', new_user_registration_path,
              class: "nav-link" %>
            </li>
          <% end %>
        </ul>   
     </div>
    </nav>
   

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    	<%= yield %>
    </div>
  </body>
</html>